### ISSUE TITLE
Question about Teensy and STM32

### ISSUE THREAD

**Issue by tvr3000** [hoantv/VNWheel#15]
Hi, great project, nice that it is open source. I have tried to compile it on platformio for Arduino Leonardo, and this compiles fine. But when I try to compile for Teensy 3.1, it fails with a  ```PluggableUSB.h: No such file or directory``` 
error. Have you tried it on a Teensy? And what STM32 board are you using?

**Comment by hoantv** [comment]
Currently it is not support teensy. Maybe i will try in the future. 
I am using stm32f407.
