### ISSUE TITLE
Increase number of buttons dont work

### ISSUE THREAD

**Issue by AlvaroWalker** [hoantv/VNWheel#16]
I tried to increase the number of buttons to 16 and 24, but it doesn't work

**Comment by hoantv** [comment]
You have to change the descriptor: report size and some function relate to button like
void Wheel_::buttons(uint8_t b) {
  _wheelReport.buttons = b;
}
void Wheel_::press(uint8_t b) {
  _wheelReport.buttons |= (uint8_t)1 << (b - 1);
}
change struct of wheelreport

**Comment by AlvaroWalker** [comment]
i changed   0x29, 0x08, // USAGE_MAXIMUM (Button 16) to   0x29, 0x10, // USAGE_MAXIMUM (Button 16)

and   0x95, 0x08, // REPORT_COUNT (8) to   0x95, 0x10, // REPORT_COUNT (8)

windows recognize 16 buttons, but arduino doenst send if pressed or not, I need to change any uint8_t var to uint16_t? or change more things on report?

**Comment by hoantv** [comment]
Yes, you have to change from uint8_t to uint16_t.
Next monday, i will release full firmware for stm32 with GUI configurator. Try it :)!

**Comment by AlvaroWalker** [comment]
i changed but dont work, i will try more code changes, anyway.

i will wait the stm32 version, will be much better! thanks

**Comment by hoantv** [comment]
> i changed but dont work, i will try more code changes, anyway.
> 
> i will wait the stm32 version, will be much better! thanks

If you want to join group test firmware. Add my fb: 

https://m.facebook.com/HoanTV
