### ISSUE TITLE
STM32

### ISSUE THREAD

**Issue by TadyTheFish** [hoantv/VNWheel#17]
Does it work with STM32? I can't compile.. USBPluggalbe.h missing. Is this Leonardo specific?

**Comment by antigravitacnik** [comment]
Afaik this version is arduino micro/leonardo specific. But there is a STM32 compatible version, but so far I think you have to write to Hoan with your hardware setup so can create .hex file for your setup.

**Comment by hoantv** [comment]
I already release fw for stm32. Check it in my repoes

**Comment by TadyTheFish** [comment]
You mean the CarSimulatorFirmware?

**Comment by hoantv** [comment]
Yes.

**Comment by TadyTheFish** [comment]
Ok thank you. I already have MMOS wheel working. I would like to implement a custom wheel. MMOS doesn't dhare his source. I was hoping that you were sharing since the leonardo code is available. But I understand that alot of gours and knowhow is in this project.

Thank you

**Comment by hoantv** [comment]
I will share the project but at right time :)

**Comment by TadyTheFish** [comment]
NICE :) When can we expect this?

**Comment by hoantv** [comment]
After it is complete :)!

**Comment by hoantv** [comment]
After it is completed. I will shared.

**Comment by hoantv** [comment]
I will shared when it is completed.
