### ISSUE TITLE
Only rfactor2 does not feel ffb or sometimes ffb disappears.

### ISSUE THREAD

**Issue by techiehong** [hoantv/VNWheel#20]
Hi. I tested the racing game with your source code.
Aceto corsa, aceto competichione, rfactor2, project cars, and urotruck.
Among them, ffb is normally operated in other games except rfactor2.
When rfactor2 tested, it seems that unlike other games, it sends ffb commands to the wheel.
There is an error in the periodic_ffb part, so it seems that it is not operating.
Have you checked the operation with this source code in rfactor 2?
I tested with source codes rfr wheel arduino and emc wheel arduino, and these two operate ffb normally in rfactor2.
You are not working on Arduino, but the above error is related to ffb, so please check it. Thanks.

**Comment by hoantv** [comment]
this project is discontinued :)
