### ISSUE TITLE
Missing file

### ISSUE THREAD

**Issue by wyatt303** [hoantv/VNWheel#9]
Hi
I cannot compile as file "filters.h" is missing. It looks like it is taken from library, but which one I should install ?

**Comment by hoantv** [comment]
Search libfilter and add it to arduino ide

**Comment by wyatt303** [comment]
I don't see such library in Arduino Manager of Libraries

**Comment by wyatt303** [comment]
Ok I've found it on github - https://github.com/MartinBloedorn/libFilter
